### ISSUE TITLE
GEM_PATH  problem. Change bin to wrapper is always necessary?

### ISSUE THREAD

**Issue by hstdt** [kattrali/cocoapods-xcode-plugin#74] opened 2015-09-25 01:26 UTC
run "which pod" in Terminal : /Users/tdt/.rvm/rubies/ruby-2.0.0-p643/**bin**/pod
insert it into GEM_PATH then update:

The command path could not be resolved
Resolved command path for "pod" is invalid.
Expanded GEM_PATH: /Users/tdt/.rvm/rubies/ruby-2.0.0-p643/**wrappers**/pod
![image](https://cloud.githubusercontent.com/assets/10215098/10091037/b2f9756c-6368-11e5-80ac-023ce79123bb.png)

But there is no folder named wrappers at /Users/tdt/.rvm/rubies/ruby-2.0.0-p643/

PS:which gem->/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/gem

**Comment by kattrali** [comment] 2015-09-25 20:23
Hi @hstdt, I could be mistaken here but I believe the message is trying to indicate that there is no directory at the path `/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/pod`. `GEM_PATH` should point to the directory containing the `pod` executable, not the executable itself. Can you try using `/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin` instead and see if that fixes your problem? I can try to make the error message more clear if that is the case.

**Comment by hstdt** [comment] 2015-09-27 01:01
Here's my folders.
![snip20150927_2](https://cloud.githubusercontent.com/assets/10215098/10120581/d3a1d514-64f5-11e5-8955-bac1ddf2a23a.png)
/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/ failed again.
![snip20150927_1](https://cloud.githubusercontent.com/assets/10215098/10120592/38e6600c-64f6-11e5-8031-d5ccfef47384.png)

**Comment by hstdt** [comment] 2015-09-27 01:20
`/Users/tdt/.rvm/wrappers/ruby-2.0.0-p643@global/`  or `$GEM_PATH/bin` can find pod ,but returns `env: bash: No such file or directory`
![snip20150927_4](https://cloud.githubusercontent.com/assets/10215098/10120643/e8a4f8e4-64f8-11e5-9f5e-1e8531c81033.png)

**Comment by kattrali** [comment] 2015-09-27 04:53
@hstdt I think I understand, though I have not been able to reproduce this yet. I am not yet sure why the resolved path for `pod` using RVM does not include the `wrappers` directory, but in the meantime I am adding a patch to not resolve RVM `bin` directories to `wrappers` directories which don't exist.

### Next Steps:

- Does `/Users/tdt/.rvm/gems/ruby-2.0.0-p643/bin`exist and work?
- Can you paste the output of `rvm debug`?
- Running `rvm repair wrappers` can fix path issues if there is a problem there as well.

**Comment by hstdt** [comment] 2015-09-28 03:02
1. `/Users/tdt/.rvm/gems/ruby-2.0.0-p643/bin`:
![image](https://cloud.githubusercontent.com/assets/10215098/10127042/aa1cce2c-65ce-11e5-9ec9-23c0e763d46b.png)
  run update: path dumplicated.
![image](https://cloud.githubusercontent.com/assets/10215098/10127081/3b8b0d88-65cf-11e5-8ba4-1a487a3affb5.png)

2. `rvm debug`->

  ```bash
ruby-2.0.0-p643:


rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
  
ruby-2.0.0-p643:

  system:
    uname:       "Darwin tdtdeMacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64"
    system:      "osx/10.10/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)"
    zsh:         "/bin/zsh => zsh 5.0.5 (x86_64-apple-darwin14.0)"

  rvm:
    version:      "rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "7 days 1 hour 4 minutes 56 seconds ago"
    path:         "/Users/tdt/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.0.0p643"
    date:         "2015-02-25"
    platform:     "x86_64-darwin14.5.0"
    patchlevel:   "2015-02-25 revision 49749"
    full_version: "ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.5.0]"

  homes:
    gem:          "/Users/tdt/.rvm/gems/ruby-2.0.0-p643"
    ruby:         "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643"

  binaries:
    ruby:         "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/ruby"
    irb:          "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/irb"
    gem:          "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/gem"
    rake:         "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin/rake"

  environment:
    PATH:         "/Users/tdt/.rvm/gems/ruby-2.0.0-p643/bin:/Users/tdt/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tdt/.rvm/bin"
    GEM_HOME:     "/Users/tdt/.rvm/gems/ruby-2.0.0-p643"
    GEM_PATH:     "/Users/tdt/.rvm/gems/ruby-2.0.0-p643:/Users/tdt/.rvm/gems/ruby-2.0.0-p643@global"
    MY_RUBY_HOME: "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643"
    IRBRC:        "/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
  PATH:
/Users/tdt/.rvm/gems/ruby-2.0.0-p643/bin:/Users/tdt/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/tdt/.rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/bin:/usr/bin
  uname -a: Darwin tdtdeMacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
  permissions: /Users/tdt/.rvm:
total 80
drwxr-xr-x  31 tdt  staff  1054  9 25 09:05 .
drwxr-xr-x+ 32 tdt  staff  1088  9 21 16:07 ..
-rw-r--r--@  1 tdt  staff  8196  9 25 09:05 .DS_Store
-rw-r--r--   1 tdt  staff   603  9 21 09:42 LICENSE
-rw-r--r--   1 tdt  staff  9706  9 21 09:42 README
-rw-r--r--   1 tdt  staff     7  9 21 09:42 RELEASE
-rw-r--r--   1 tdt  staff     8  9 21 09:42 VERSION
drwxr-xr-x   6 tdt  staff   204  9 21 10:11 archives
drwxr-xr-x  11 tdt  staff   374  9 21 09:42 bin
drwxr-xr-x  14 tdt  staff   476  9 21 10:11 config
drwxr-xr-x   6 tdt  staff   204  9 21 09:42 contrib
drwxr-xr-x   5 tdt  staff   170  9 21 09:42 docs
drwxr-xr-x   5 tdt  staff   170  9 21 10:11 environments
drwxr-xr-x   3 tdt  staff   102  9 21 09:42 examples
drwxr-xr-x   5 tdt  staff   170  9 21 09:42 gem-cache
drwxr-xr-x   6 tdt  staff   204  9 25 09:15 gems
drwxr-xr-x   6 tdt  staff   204  9 21 09:42 gemsets
drwxr-xr-x  46 tdt  staff  1564  9 21 09:42 help
drwxr-xr-x  14 tdt  staff   476  9 21 09:42 hooks
-rw-r--r--   1 tdt  staff    11  9 21 09:42 installed.at
drwxr-xr-x   4 tdt  staff   136  9 21 09:42 lib
drwxr-xr-x   4 tdt  staff   136  9 21 10:11 log
drwxr-xr-x   3 tdt  staff   102  9 21 09:42 man
drwxr-xr-x  10 tdt  staff   340  9 21 09:42 patches
drwxr-xr-x   5 tdt  staff   170  9 21 09:42 patchsets
drwxr-xr-x   5 tdt  staff   170  9 25 09:05 rubies
drwxr-xr-x  52 tdt  staff  1768  9 21 09:42 scripts
drwxr-xr-x   5 tdt  staff   170  9 21 10:11 src
drwxr-xr-x   2 tdt  staff    68  9 21 10:11 tmp
drwxr-xr-x   8 tdt  staff   272  9 21 10:11 user
drwxr-xr-x   5 tdt  staff   170  9 21 10:11 wrappers

/Users/tdt/.rvm/rubies:
total 32
drwxr-xr-x   5 tdt  staff    170  9 25 09:05 .
drwxr-xr-x  31 tdt  staff   1054  9 25 09:05 ..
-rw-r--r--@  1 tdt  staff  10244  9 25 09:05 .DS_Store
lrwxr-xr-x   1 tdt  staff     38  9 21 10:11 default -> /Users/tdt/.rvm/rubies/ruby-2.0.0-p643
drwxr-xr-x   9 tdt  staff    306  9 25 09:05 ruby-2.0.0-p643

  uname -r: 10.10
  uname -m: x86_64
  sw_vers: ProductName:	Mac OS X,ProductVersion:	10.10.5,BuildVersion:	14F27,
  ARCHFLAGS: 
  LDFLAGS: 
  CFLAGS: 
  /Developer/SDKs/*:*,

/Users/tdt/.bashrc:
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
/Users/tdt/.bash_profile:
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
/Users/tdt/.rvm/config/alias \(filtered\):
default=ruby-2.0.0-p643

/Users/tdt/.rvm/config/db \(filtered\):
#General
niceness=0
# Rubies
interpreter=ruby
default_ruby=ruby
ruby_repo_url=git://github.com/ruby/ruby.git
ruby_url=http://cache.ruby-lang.org/pub/ruby
ruby_url_fallback_1=http://ftp.ruby-lang.org/pub/ruby
ruby_url_fallback_2=http://www.mirrorservice.org/sites/ftp.ruby-lang.org/pub/ruby
unmaintained_ruby=1.9.3
unmaintained_date=2014-02-23
ruby_version=2.2.1
ruby_2.0.0_patch_level=p643
ruby_1.9.3_patch_level=p551
ruby_1.9.2_patch_level=p330
ruby_1.9.1_patch_level=p431
ruby_1.8.7_patch_level=head
ruby_1.8.6_patch_level=p420
ruby_1.8.5_patch_level=p231
CentOS_5_ruby_1.9.2_patch_level=p320
CentOS_5_ruby_1.9.2_patch_level_warn=Warning, Centos 5 can not build head version of ruby, falling back to latest patchlevel, your ruby will be less secure bacuase of this.
CentOS_5_ruby_1.8.7_patch_level=p374
CentOS_5_ruby_1.8.7_patch_level_warn=Warning, Centos 5 can not build head version of ruby, falling back to latest patchlevel, your ruby will be less secure bacuase of this.
rubygems_url=http://production.cf.rubygems.org/rubygems
rubygems_url_fallback_1=https://github.com/rubygems/rubygems/archive/v.tar.gz
rubygems_url_fallback_1_pattern=http://production.cf.rubygems.org/rubygems/rubygems-([[:digit:]\.]+).tgz
rubygems_repo_url=git://github.com/rubygems/rubygems.git
rubygems_version=latest-2.4
ree_1.8.6_rubygems_version=1.3.7
ree_1.8.7_rubygems_version=latest-2.0
ruby_1.8.4_rubygems_version=1.3.5
ruby_1.8.5_rubygems_version=1.3.5
ruby_1.8.6_rubygems_version=1.3.7
ruby_1.8.7_rubygems_version=latest-2.0
ruby_1.9.1_rubygems_version=latest-1.8
ruby_head_rubygems_version=head
gem_gem-wrappers_version=>=1.2.7
gem_gem-empty_version=>=1.0.0
gem_rdoc_version=>=4.1.1
gem_rvm_version=>=1.11.3.9
rbx_version=2.5.2
rbx_1.0.0_patch_level=20100514
rbx_1.0.1_patch_level=20100603
rbx_1.1.0_patch_level=20100923
rbx_1.1.1_patch_level=20101116
rbx_1.2.0_patch_level=20101221
rbx_1.2.1_patch_level=20110215
rbx_1.2.2_patch_level=20110222
rbx_1.2.3_patch_level=20110315
rbx_1.2.4_patch_level=20110705
rbx_url=http://asset.rubini.us
rbx_2.0.0_url=http://releases.rubini.us
rubinius_repo_url=git://github.com/rubinius/rubinius.git
ree_version=1.8.7
ree_configure_flags=--dont-install-useful-gems
ree_1.8.6_patch_level=20090610
ree_1.8.6_url=http://rubyforge.org/frs/download.php/58677
ree_1.8.6_repo_url=git://github.com/FooBarWidget/rubyenterpriseedition.git
ree_1.8.7_url=http://rubyenterpriseedition.googlecode.com/files
ree_1.8.7_repo_url=git://github.com/FooBarWidget/rubyenterpriseedition187-330
ree_1.8.7_patch_level=2012.02
ree_1.8.7_2010.02_url=http://rubyforge.org/frs/download.php/71096
mruby_repo_url=git://github.com/mruby/mruby.git
mruby_url=https://github.com/mruby/mruby/archive
mruby_version=1.0.0
jruby_version=1.7.19
jruby_repo_url=git://github.com/jruby/jruby.git
jruby_url=http://jruby.org.s3.amazonaws.com/downloads
macruby_version=0.12
macruby_0.10_url=http://macruby.macosforge.org/files
macruby_url=https://github.com/downloads/MacRuby/MacRuby
macruby_repo_url=git://github.com/MacRuby/MacRuby.git
macruby_nightly_url=http://macruby.jp/files/nightlies
maglev_version=head
maglev_url=http://seaside.gemtalksystems.com/maglev
maglev_repo_url=git://github.com/MagLev/maglev.git
ironruby_version=1.1.3
ironruby_repo_url=git://github.com/ironruby/ironruby.git
ironruby_1.1.3_url=http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=ironruby&DownloadId=217153&FileTime=129445296766130000&Build=19727
topaz_version=head
topaz_repo_url=git://github.com/topazproject/topaz.git
topaz_url=http://builds.topazruby.com
rvm_remote_server_url=https://rvm_io.global.ssl.fastly.net/binaries
rvm_remote_server_url1=https://s3.amazonaws.com/jruby.org
rvm_remote_server_path1=downloads
rvm_remote_server_url2=http://binaries.rubini.us
rvm_remote_server_url3=https://rubies.travis-ci.org
# rvm_remote_server_url4=http://gentoo-binaries.my-custom-server.com
# rvm_remote_server_path4=ec2-2013.09
# Packages
readline_url=http://ftp.gnu.org/gnu/readline
libiconv_url=http://ftp.gnu.org/pub/gnu/libiconv
curl_url=http://curl.haxx.se/download
openssl_url=http://www.openssl.org/source
openssl_version=1.0.1i
zlib_url=http://prdownloads.sourceforge.net/libpng
autoconf_url=http://ftp.gnu.org/gnu/autoconf
ncurses_url=http://ftp.gnu.org/pub/gnu/ncurses
pkg-config_url=http://pkgconfig.freedesktop.org/releases
gettext_url=http://ftp.gnu.org/pub/gnu/gettext
libxml2_url=ftp://xmlsoft.org/libxml2
libxslt_url=ftp://xmlsoft.org/libxslt
yaml_url=http://pyyaml.org/download/libyaml
yaml_version=0.1.6
glib_url=http://ftp.gnome.org/pub/gnome/sources/glib/2.23
mono_url=http://ftp.novell.com/pub/mono/sources/mono
llvm_url=https://llvm.org/svn/llvm-project/llvm/trunk
# CentOS / Fedora EPEL
epel6_i386_rpm=https://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
epel6_x86_64_rpm=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
epel5_i386_rpm=https://dl.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
epel5_x86_64_rpm=https://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
maven_version=3.1.1

/Users/tdt/.gemrc \(filtered\):
---
:backtrace: false
:bulk_threshold: 1000
:sources:
- http://ruby.taobao.org/
:update_sources: true
:verbose: true

gem sources:
```
3. `rvm repair wrappers`: Need I fix it?
```bash
tdtdeMacBook-Pro:carthage tdt$ sudo -s
Password:
bash-3.2# rvm repair wrappers

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

Hint: To fix PATH errors try using 'rvmsudo' instead of 'sudo', see:
    http://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm/28080063#28080063

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
Regenerating all wrappers...
Regenerating wrappers for ruby-2.0.0-p643..............................................................
Regenerating wrappers for ruby-2.0.0-p643@global..............................................................
Wrappers regenerated
```

**Comment by hstdt** [comment] 2015-09-28 03:35
After I run `rvm 2.0.0 --default` 

`/Users/tdt/.rvm/gems/ruby-2.0.0-p643/bin`can update,but says:
```
/Users/tdt/.rvm/gems/ruby-2.0.0-p643/wrappers/pod update --no-repo-update
env: bash: No such file or directory
```

**Comment by kattrali** [comment] 2015-09-28 04:06
@hstdt Oh my. :/ I'm unsure how to proceed here, it definitely appears to be an issue with RVM instead of the plugin. I recommend trying to install cocoapods with system ruby since running manually does not work either.

**Comment by hstdt** [comment] 2015-09-29 02:30
I tried many ways to solve it ,but failed.It seems that I have to give up..
In my last Mac,the same way to install ruby ,set path ` $GEM_PATH/bin` and it works well.It's really confusing.
Thanks for your help.If I find the reason,I'll tell you.

**Comment by kattrali** [comment] 2015-09-29 03:47
@hstdt Alright, please let me know if you figure it out. Closing this issue for now, but will reopen if we find additional ways to test for this.

**Closed by kattrali** 2015-09-29 03:47 UTC

**Comment by hstdt** [comment] 2015-10-10 08:10
OK,I find the reason...I moved Xcode.app to a folder in Application,so ...

**Comment by kattrali** [comment] 2015-10-10 19:22
Ah, good to know. Thanks for the follow up!
